version:    0.1.1.0
name:       project-euler
github:     "mel-brown/project-euler"
license:    BSD3
author:     "Melanie Brown"
maintainer: "brown.m@pm.me"
copyright:  "2020 Melanie Brown"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mel-brown/project-euler#readme>

dependencies:
  - arithmoi
  - async
  - base
  - containers
  - combinat
  - deepseq
  - exact-combinatorics
  - lens
  - linear
  - mtl
  - numbers
  - primes
  - time
  - toolbox
  - vector

default-extensions:
  - LambdaCase
  - MultiWayIf
  - TupleSections
  - RecordWildCards
  - BangPatterns
  - ViewPatterns
  - TypeOperators
  - KindSignatures
  - InstanceSigs
  - OverloadedStrings
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable

library:
  source-dirs: src

executables:
  project-euler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - project-euler

# tests:
#   project-euler-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - project-euler
